import { ToastContainer } from "react-toastify";
import { TopBar } from "./components";
import "./globals.css";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
// All packages except `@mantine/hooks` require styles imports

// // const theme = createTheme({
// //   /** Put your mantine theme override here */
// // });

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <MantineProvider theme={theme}>
//           {children}
//           <Navbar />
//           <ToastContainer />
//         </MantineProvider>
//       </body>
//     </html>
//   );
// }
// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import "@mantine/core/styles.css";

import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { Navbar } from "./components/navbar/Navbar";

export const metadata = {
  title: "My Mantine app",
  description: "I have followed setup instructions carefully",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <Navbar />
          {children}
          <ToastContainer />
        </MantineProvider>
      </body>
    </html>
  );
}
